catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/starlight': ^0.37.6
  "@types/node": ^20.17.1
  astro: ^5.17.2
  typescript: ^5.7.3

catalogs:
  ec:
    astro-expressive-code: ^0.41.6
    rehype-expressive-code: ^0.41.6
  mdast:
    mdast-util-from-markdown: ^2.0.2
    mdast-util-gfm: ^3.1.0
    mdast-util-to-hast: ^13.2.1
  min:
    '@expressive-code/core': "^0.41.6"
    expressive-code: "^0.41.6"
    typescript: ^5.7.3
  twoslash:
    twoslash: ^0.3.6
    twoslash-vue: ^0.3.6

packages:
  - package
  - docs
  - playground

linkWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp

preferWorkspacePackages: true

saveWorkspaceProtocol: false
