/**
 * This script takes a TypeScript file as input, minifies it using tsdown, and outputs the minified code as a JavaScript module.
 * The output file will have the same name as the input file but with a .min.ts extension.
 *
 * Usage:
 *   node minify.ts <input-file.ts> <output-file-path.ts> --log-level warn
 *
 * The --log-level flag is optional and can be set to "warn", "silent", "error", or "info" to control the logging level of the tsdown build process.
 *
 * Example:
 *   node minify.ts ./js-modules/popup.ts ./src/module-code/popup.min.ts --log-level warn
 *
 * This will take the popup.ts file, minify it, and output the result to popup.min.ts.
 *
 * Note: The output file will be a JavaScript module that exports the minified code as a default export string.
 * The script also adds a header comment to the output file indicating that it is generated and should not be edited directly.
 *
 * @module minify
 * @author Adam Matthiesen
 * @license MIT
 * @description A script to minify TypeScript files using tsdown and output them as JavaScript modules.
 */

import { writeFileSync } from "node:fs";
import { styleText } from "node:util";
import { build } from "tsdown";

// Get file parameter from command line arguments
const filePath = process.argv[2];
console.log(`${styleText("blue", "ℹ")} Processing file: ${filePath}`);

const sourceFileWithoutPath = filePath.split("/").pop() || filePath;

// Get the folder path of the input file
const outFilePath = process.argv[3];
console.log(`${styleText("blue", "ℹ")} Output file path: ${outFilePath}`);

// Parse --log-level flag from command line arguments
const logLevelIndex = process.argv.indexOf("--log-level");
const logLevel =
	logLevelIndex !== -1 && process.argv[logLevelIndex + 1]
		? process.argv[logLevelIndex + 1]
		: "warn";

// Generate markdown output
const output: string[] = [];

// Add file header to output
output.push(
	"/*",
	"	GENERATED FILE - DO NOT EDIT",
	"	----------------------------",
	`	This JS module code was built from the source file "${sourceFileWithoutPath}".`,
	"	To change it, modify the source file and then re-run the build script.",
	"*/",
	"",
);

// Build the minified code using tsdown
const buildResult = await build({
	entry: filePath,
	format: "esm",
	dts: false,
	minify: true,
	outDir: "./_temp/minify",
	logLevel: logLevel as "warn" | "silent" | "error" | "info",
});

// Validate the build result
if (buildResult.length === 0) {
	console.error(`${styleText("red", "✖")} No output generated by tsdown build.\n`);
	process.exit(1);
}

// Extract the minified code from the build result
const firstChunk = buildResult[0].chunks[0];
if (!firstChunk || firstChunk.type !== "chunk") {
	console.error(`${styleText("red", "✖")} Unexpected output format from tsdown build.\n`);
	process.exit(1);
}
const result = firstChunk.code;

// Report build success
if (!result) {
	console.error(`${styleText("red", "✖")} Failed to process tsdown build result.`);
} else {
	console.log(`${styleText("green", "✔")} Minified code generated successfully.`);
}

// Add the minified code to the output
output.push(`export default '${result}';`);

// Write output to file
writeFileSync(outFilePath, output.join("\n"));

// Report file write success
console.log(`${styleText("green", "✔")} Minified code written to ${outFilePath}`);
