import { writeFileSync } from "node:fs";
import { build } from "tsdown";

// Generate markdown output
const output: string[] = [];

// Add file header to output
output.push(
	"/*",
	"	GENERATED FILE - DO NOT EDIT",
	"	----------------------------",
	'	This JS module code was built from the source file "popup.ts".',
	"	To change it, modify the source file and then re-run the build script.",
	"*/",
	"",
);

// Build the minified code using tsdown
const buildResult = await build({
	entry: "./src/module-code/popup.ts",
	format: "esm",
	dts: false,
	minify: true,
	outDir: "./_temp/minify",
});

// Validate the build result
if (buildResult.length === 0) {
	console.error("No output generated by tsdown build.");
	process.exit(1);
}

// Extract the minified code from the build result
const firstChunk = buildResult[0].chunks[0];
if (!firstChunk || firstChunk.type !== "chunk") {
	console.error("Unexpected output format from tsdown build.");
	process.exit(1);
}
const result = firstChunk.code;

// Report build success
if (!result) {
	console.error("✖ Failed to process tsdown build result.");
} else {
	console.log("✔ Minified code generated successfully.");
}

// Add the minified code to the output
output.push(`export default '${result}';`);

// Write output to file
writeFileSync("./src/module-code/popup.min.ts", output.join("\n"));

console.log("Minified code written to ./src/module-code/popup.min.ts");
