name: Tests with Allure Report

on:
  push:
    branches: [main]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Apollo Git Bot
        id: bot-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.STUDIOCMS_GIT_BOT_APP_ID }}
          private-key: ${{ secrets.STUDIOCMS_GIT_BOT_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          token: ${{ steps.bot-token.outputs.token }}

      - name: Checkout History branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: test-history
          path: test-history
          persist-credentials: false
          token: ${{ steps.bot-token.outputs.token }}

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@2f4fab1a66855feadec9e960bdbdc4368c23aa18 # main

      - name: Build packages
        run: pnpm ci:build

      - name: Run tests and generate report
        run: pnpm ci:test

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ steps.bot-token.outputs.token }}
          publish_branch: test-report
          publish_dir: ./allure-report

      - name: Upload History file
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ steps.bot-token.outputs.token }}
          publish_branch: test-history
          publish_dir: ./test-history
